# Generated by Django 5.0.2 on 2025-12-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_id_alter_user_account_number'),
        ('users', '0005_alter_user_email'),
    ]

    operations = [
    ]
