# Generated by Django 5.2.7 on 2025-12-11 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('user', models.OneToOneField(db_column='account_number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='revenue', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
