# Generated by Django 5.2.7 on 2025-12-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_moneyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
