# Generated by Django 5.2.7 on 2025-12-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_moneyrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoneyRequest',
        ),
    ]
