"""
Django settings for diuwallet project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from logging import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True) 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dmopjp=4met6el8$&#7t_*9v5#ij!$%34b+gmjjr(wo93tsaqq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'users',
    'wallet',
    'agent',
    'merchant',
    'panel_admin',
    # 'customer',
    'transactions',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'customer.apps.CustomerConfig',
    'django_apscheduler',
    'corsheaders',
    
    
    
    
]
AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

REST_FRAMEWORK = {
   
    'DEFAULT_AUTHENTICATION_CLASSES': (
        
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}
CORS_ORIGIN_ALLOW_ALL = True
ROOT_URLCONF = 'diuwallet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'diuwallet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'diuwallet_db',
        'USER': 'postgres',
        'PASSWORD': 'NotunPassword123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    'BLACKLIST_AFTER_ROTATION': True,
    'USER_ID_FIELD': 'account_number',
    
    'USER_ID_CLAIM': 'account_number',  # or 'account_number'account number k primary key hisahbe use korchi tai ,karin default vabe jwt id k pk dhore ney . 
    
    }
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
   
    "handlers": {
        "console": {"class": "logging.StreamHandler",
                    "formatter": "verbose"
        },
        
        # "error_file": {
        #     "class": "logging.FileHandler",
        #     "filename": os.path.join(LOG_DIR, "errors.log"),
        #     "formatter": "verbose",
        #     "level": "ERROR",
        #     "propagate": False,
        # },
        "transaction_file": {
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "transactions.log"),
            "formatter": "verbose",
            "level": "ERROR",
            
           
        },
        "security_file": {
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "security.log"),
            "formatter": "verbose",
            "level": "INFO",
            
            
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "transaction_file","security_file"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
        },
        "transactions_logger":{
            "handlers" : ["transaction_file","console"],
            "level" : "INFO",
            "propagate": False,
        },
        "security_logger":{
            "handlers" : ["security_file","console"],
            "level" : "INFO",
            "propagate" : False, #propagate false korlam jate duplicate na hoy log gulo
        },
        # "error_logger":{
        #     "handlers" : ["error_file","console"],
        #     "level" : "ERROR",
        #     "propagate": False,
        # },
            
    },
    "formatters": {
        "verbose": {
            "format": "[{lineno}] {asctime} -- ({levelname})- {name}- {message}",
            "style": "{",
        }
    },
    
}



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
print("LOG_DIR:", LOG_DIR)
print("SECURITY LOG PATH:", os.path.join(LOG_DIR, "security.log"))